### ISSUE TITLE
What is runWidget in your examples?

### ISSUE THREAD

**Issue by dumptyhumpty2014gmail** [ditman/flutter-experimental#1]
Sorry I try to build your examples but I have error that "The function 'runWidget' isn't defined.
Try importing the library that defines 'runWidget', correcting the name to the name of an existing function, or defining a function named 'runWidget'"
If I change it to "runApp" I have error in ui_web

**Comment by ditman** [comment]
@dumptyhumpty2014gmail you should be using the `master` channel of flutter to have `runWidget`; it has to do with cross-platform multi-view support.

Check this doc and let me know if it has enough information (there's a specific section about `runWidget`):

* https://docs.google.com/document/d/13E27tD8_9f6lDgwg3MpGNTV8XIRCZH3ByI-t9kI9IUM/edit?usp=sharing

**Comment by dumptyhumpty2014gmail** [comment]
Thx I use Flutter 3.19.6 but don't have runWidget I try to deal with the problem

**Comment by ditman** [comment]
@dumptyhumpty2014gmail yeah, it's probably only available in the `beta`/`master` channel until the next release.

Please update to `beta` or `master` to try the examples.
